# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contacts_pb2 as contacts__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contacts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContactServiceStub(object):
    """--- Definição do Serviço ---

    O serviço define os "endpoints" ou métodos da nossa API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddContact = channel.unary_unary(
                '/contacts.ContactService/AddContact',
                request_serializer=contacts__pb2.AddContactRequest.SerializeToString,
                response_deserializer=contacts__pb2.Contact.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/contacts.ContactService/GetContact',
                request_serializer=contacts__pb2.GetContactRequest.SerializeToString,
                response_deserializer=contacts__pb2.Contact.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/contacts.ContactService/ListContacts',
                request_serializer=contacts__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=contacts__pb2.ListContactsResponse.FromString,
                _registered_method=True)


class ContactServiceServicer(object):
    """--- Definição do Serviço ---

    O serviço define os "endpoints" ou métodos da nossa API.
    """

    def AddContact(self, request, context):
        """Operação para adicionar um novo contato.
        Recebe um AddContactRequest e retorna o Contact criado (com id).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Operação para consultar um contato pelo seu ID.
        Recebe um GetContactRequest e retorna o Contact encontrado.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Operação para listar todos os contatos cadastrados.
        Recebe uma requisição vazia e retorna uma lista de contatos.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=contacts__pb2.AddContactRequest.FromString,
                    response_serializer=contacts__pb2.Contact.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=contacts__pb2.GetContactRequest.FromString,
                    response_serializer=contacts__pb2.Contact.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=contacts__pb2.ListContactsRequest.FromString,
                    response_serializer=contacts__pb2.ListContactsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contacts.ContactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contacts.ContactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactService(object):
    """--- Definição do Serviço ---

    O serviço define os "endpoints" ou métodos da nossa API.
    """

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactService/AddContact',
            contacts__pb2.AddContactRequest.SerializeToString,
            contacts__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactService/GetContact',
            contacts__pb2.GetContactRequest.SerializeToString,
            contacts__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactService/ListContacts',
            contacts__pb2.ListContactsRequest.SerializeToString,
            contacts__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
