# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: contacts.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'contacts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontacts.proto\x12\x08\x63ontacts\"@\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.contacts.PhoneType\"p\n\x07\x43ontact\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12%\n\x06phones\x18\x03 \x03(\x0b\x32\x15.contacts.PhoneNumber\x12$\n\x08\x63\x61tegory\x18\x04 \x01(\x0e\x32\x12.contacts.Category\"n\n\x11\x41\x64\x64\x43ontactRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x06phones\x18\x02 \x03(\x0b\x32\x15.contacts.PhoneNumber\x12$\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x12.contacts.Category\"\x1f\n\x11GetContactRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x15\n\x13ListContactsRequest\";\n\x14ListContactsResponse\x12#\n\x08\x63ontacts\x18\x01 \x03(\x0b\x32\x11.contacts.Contact*L\n\x08\x43\x61tegory\x12\x18\n\x14\x43\x41TEGORY_UNSPECIFIED\x10\x00\x12\n\n\x06\x46\x41MILY\x10\x01\x12\x0c\n\x08PERSONAL\x10\x02\x12\x0c\n\x08\x42USINESS\x10\x03*G\n\tPhoneType\x12\x1a\n\x16PHONE_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06MOBILE\x10\x01\x12\x08\n\x04HOME\x10\x02\x12\x08\n\x04WORK\x10\x03\x32\xe1\x01\n\x0e\x43ontactService\x12>\n\nAddContact\x12\x1b.contacts.AddContactRequest\x1a\x11.contacts.Contact\"\x00\x12>\n\nGetContact\x12\x1b.contacts.GetContactRequest\x1a\x11.contacts.Contact\"\x00\x12O\n\x0cListContacts\x12\x1d.contacts.ListContactsRequest\x1a\x1e.contacts.ListContactsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contacts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORY']._serialized_start=437
  _globals['_CATEGORY']._serialized_end=513
  _globals['_PHONETYPE']._serialized_start=515
  _globals['_PHONETYPE']._serialized_end=586
  _globals['_PHONENUMBER']._serialized_start=28
  _globals['_PHONENUMBER']._serialized_end=92
  _globals['_CONTACT']._serialized_start=94
  _globals['_CONTACT']._serialized_end=206
  _globals['_ADDCONTACTREQUEST']._serialized_start=208
  _globals['_ADDCONTACTREQUEST']._serialized_end=318
  _globals['_GETCONTACTREQUEST']._serialized_start=320
  _globals['_GETCONTACTREQUEST']._serialized_end=351
  _globals['_LISTCONTACTSREQUEST']._serialized_start=353
  _globals['_LISTCONTACTSREQUEST']._serialized_end=374
  _globals['_LISTCONTACTSRESPONSE']._serialized_start=376
  _globals['_LISTCONTACTSRESPONSE']._serialized_end=435
  _globals['_CONTACTSERVICE']._serialized_start=589
  _globals['_CONTACTSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
